Mercadito/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from administracion.views import *

from django.contrib.auth.decorators import login_required #para que sea login


urlpatterns = [
    path('', admin.site.urls),
    path('inventario', login_required(ProductosGeneralPDF.as_view()), name='inventario'),
    path('informe/<int:pk>', login_required(ComprasYVentasPDF.as_view()), name='informe'),  
    path('comprovante/<int:pk>', login_required(ComprovantePDF.as_view()), name='comprovante'),  
    path('comprovanteescuela/<int:pk>', login_required(ComprovanteEscuelaPDF.as_view()), name='comprovanteescuela'),  

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ventas/models.py
# -*- coding: utf-8 -*-
from django.db import models

from administracion.models import *
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe

class Venta(models.Model): 
	cliente=models.CharField('Cliente', max_length=150, null=False)
	nit = models.CharField('NIT', max_length=15, null=False)
	fecha=models.DateField('Fecha', auto_now_add=True)
	total=models.DecimalField('Total', max_digits=7, decimal_places=2, default  =0.00)

	def __str__(self):
		return "%s %s %s %s" %(self.cliente, self.id, self.total, self.fecha)

	def generar_comprovante(self):
			return mark_safe('<a target="_blank" href="/comprovante/'+str(self.id)+'"class="informe">Imprimir</a>')


	class Meta():
		db_table = 'venta'
		verbose_name = 'Venta'
		verbose_name_plural = 'Ventas'


class DetalleVenta(models.Model,):
	venta=models.ForeignKey(Venta, on_delete=models.CASCADE, null=False)
	producto=models.ForeignKey(Producto, on_delete=models.CASCADE, null=False)
	cantidad= models.PositiveIntegerField('Cantidad')
	sub_total=models.DecimalField('Sub Total', max_digits=7, decimal_places=2, default  =0.00)

	def clean(self):
		super(DetalleVenta, self).clean()

		if (self.producto.existencia<self.cantidad ):
			raise ValidationError('No posee suficiente Exitencia para completar la Venta')



	def save (self, force_insert=False, force_update=False, using=None):

		# metodo para la operación del subtotal
		self.sub_total = (self.cantidad * self.producto.precio_venta)

		# metodo para sumar las existencias del producto
		product = Producto.objects.filter(nombre = self.producto).first()
		product.existencia = (product.existencia - self.cantidad)
		print(product.existencia)
		product.save()

		# metodo para sumar el total de Comprobantecompra
		comprobante = Venta.objects.all().last()
		comprobante.total = (comprobante.total + self.sub_total)
		comprobante.save()

		super(DetalleVenta, self).save(force_insert, force_update, using)



	def delete (self, *args, **kwargs):

		# metodo para restar existencias cuando se le resta la cantidad
		product = Producto.objects.filter(nombre = self.producto).first()
		product.existencia = (product.existencia + self.cantidad)
		print(product.existencia)
		product.save()

		# metodo para restar total cuando se elimina existencias
		comprobante = Venta.objects.all().last()
		comprobante.total = (comprobante.total - self.sub_total)
		comprobante.save()


		super(DetalleVenta, self).delete(*args, **kwargs)



	class Meta():
		db_table = 'detalle_venta'
		verbose_name = 'Detalle de Venta'
		verbose_name_plural = 'Detalles de Ventas'




class VentaEscuela(models.Model): 
	escuela=models.ForeignKey(Escuela, on_delete=models.CASCADE, null=False)
	fecha=models.DateField('Fecha', auto_now_add=True)
	total=models.DecimalField('Total', max_digits=7, decimal_places=2, default  =0.00)

	def __str__(self):
		return "%s %s %s %s" %(self.escuela.nombre, self.id, self.total, self.fecha)

	def generar_comprovante(self):
			return mark_safe('<a target="_blank" href="/comprovanteescuela/'+str(self.id)+'"class="informe">Imprimir</a>')


	class Meta():
		db_table = 'venta_escuela'
		verbose_name = 'Venta a Escuela'
		verbose_name_plural = 'Ventas a Escuelas'


class DetalleVentaEscuela(models.Model,):
	venta_escuela=models.ForeignKey(VentaEscuela, on_delete=models.CASCADE, null=False)
	producto=models.ForeignKey(Producto, on_delete=models.CASCADE, null=False)
	cantidad= models.PositiveIntegerField('Cantidad')
	sub_total=models.DecimalField('Sub Total', max_digits=7, decimal_places=2, default  =0.00)

	def clean(self):
		super(DetalleVentaEscuela, self).clean()

		if (self.producto.existencia<self.cantidad ):
			raise ValidationError('No posee suficiente Exitencia para completar la Venta')


	def save (self, force_insert=False, force_update=False, using=None):

		# metodo para la operación del subtotal
		self.sub_total = (self.cantidad * self.producto.precio_venta)

		# metodo para sumar las existencias del producto
		product = Producto.objects.filter(nombre = self.producto).first()
		product.existencia = (product.existencia - self.cantidad)
		print(product.existencia)
		product.save()

		# metodo para sumar el total de Comprobantecompra
		comprobante = VentaEscuela.objects.all().last()
		comprobante.total = (comprobante.total + self.sub_total)
		comprobante.save()

		super(DetalleVentaEscuela, self).save(force_insert, force_update, using)



	def delete (self, *args, **kwargs):

		# metodo para restar existencias cuando se le resta la cantidad
		product = Producto.objects.filter(nombre = self.producto).first()
		product.existencia = (product.existencia + self.cantidad)
		print(product.existencia)
		product.save()

		# metodo para restar total cuando se elimina existencias
		comprobante = VentaEscuela.objects.all().last()
		comprobante.total = (comprobante.total - self.sub_total)
		comprobante.save()


		super(DetalleVentaEscuela, self).delete(*args, **kwargs)



	class Meta():
		db_table = 'detalle_venta_escuela'
		verbose_name = 'Detalle de Venta a Escuelas'
		verbose_name_plural = 'Detalles de Ventas a Escuelas'




templates/principal/ComprovanteVenta.html
<!DOCTYPE html>
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style type="text/css">
    
    .img {
        width: 8cm;
        text-align: center;
        margin: 0;
        }

        #invoice thead tr th {
        text-align: left;
        border-bottom: 1px solid black;
        border-top: 1px solid black;
        padding-top: 4px;
    }

    #invoice thead tr {
        margin-bottom: 0;
        padding-bottom: 0;
    }

    #invoice tbody tr {
        padding: 6px;
    }

    .titulo {
                color: black;
                font-size: 6;
                text-align: center;
                
            }


    .titulo2 {

                color: black;
                text-align: right;

            }
    .cliente {

                font-size: 4;
                color: black;
                text-align: left;
             }

    .titulo3 {  
                
                color: black;
                text-align: center;

     

    }
    .producto {

                border: #BFC9CA 2px solid;
                border-collapse: separate;
                border-spacing: 20px 10px;
                font-size: 4;
                color: #154360;
                height: 16;
             }

</style>
</head>

<body>
    <p style="justify-content: center; text-align: center;"><img src="{{ icon }}" class="img">
             <br></p>


<p class="head">
    <h1 class="titulo"><img src="LogoFarmacia2.png" height="90px">SUPERMERCADO MARY
        <br> Quezaltepeque, Chiquimula
        </h1>
    

        <div>
            <h1 class="titulo2">COMPROBANTE DE VENTA    No. {{venta.id}}</h1>
            <table class="cliente">
                <tr>
                    <th>
                        Cliente:
                    </th>
                    
                    <td >
                        {{venta.cliente}}
                    </td>             
                </tr>
                <tr>
                    <th>
                        NIT
                    </th>
                    
                    <td >
                        {{venta.nit}}
                    </td>             
                </tr>
                <tr>
                    <th>
                        Fecha
                    </th>
                    
                    <td >
                        {{venta.fecha}}
                    </td>             
                </tr>
                </tr>
            </table>
            <h1>_____________________________________________________________________________________________</h1>
            <h1 class="titulo3">Listado de Productos</h1>

 <table id="invoice">
    <thead>
    <tr>
        <th style="width: 60%;">NOMBRE PRODUCTO</th>
        <th style="width: 60%;">MARCA</th>
        <th style="width: 20%;">CANTIDAD</th>
        <th style="width: 20%;">SUBTOTAL</th>
    </tr>

    </thead>
    <tbody>
        <tr>
    {% for d in venta.detalleventa_set.all %}
            <td>{{ d.producto.nombre }}</td>
            <td>{{ d.producto.marca }}</td>
            <td>{{ d.cantidad}}</td>
            <td>Q.{{ d.sub_total}}</td>

        </tr>

        <table id="invoice">
        <th style="background-color: none; width:80%; font-size: 14px">Total</th>
        <th style="background-color: none; font-size: 14px">Q.{{venta.total}}</th>
    </table>
    
    {% endfor %}

<br><br><h1 style="text-align: center;">***** Gracias por su compra, es un gusto atenderle *****</h1>

</p><br>




   

    
</body>
</html>

templates/principal/ComprovanteVentaEscuela.html
<!DOCTYPE html>
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style type="text/css">
    
    .img {
        width: 8cm;
        text-align: center;
        margin: 0;
        }

        #invoice thead tr th {
        text-align: left;
        border-bottom: 1px solid black;
        border-top: 1px solid black;
        padding-top: 4px;
    }

    #invoice thead tr {
        margin-bottom: 0;
        padding-bottom: 0;
    }

    #invoice tbody tr {
        padding: 6px;
    }

    .titulo {
                color: black;
                font-size: 6;
                text-align: center;
                
            }


    .titulo2 {

                color: black;
                text-align: right;

            }
    .cliente {

                font-size: 4;
                color: black;
                text-align: left;
             }

    .titulo3 {  
                
                color: black;
                text-align: center;

     

    }
    .producto {

                border: #BFC9CA 2px solid;
                border-collapse: separate;
                border-spacing: 20px 10px;
                font-size: 4;
                color: #154360;
                height: 16;
             }

</style>
</head>

<body>
    <p style="justify-content: center; text-align: center;"><img src="{{ icon }}" class="img">
             <br></p>


<p class="head">
    <h1 class="titulo"><img src="LogoFarmacia2.png" height="90px">SUPERMERCADO MARY
        <br> Quezaltepeque, Chiquimula
        </h1>
    

        <div>
            <h1 class="titulo2">COMPROBANTE DE VENTA    No. {{venta.id}}</h1>
            <table class="cliente">
                <tr>
                    <th>
                        Cliente:
                    </th>
                    
                    <td >
                        {{venta.escuela.nombre}}
                    </td>             
                </tr>
                <tr>
                    <th>
                        NIT
                    </th>
                    
                    <td >
                        {{venta.escuela.nit}}
                    </td>             
                </tr>
                <tr>
                    <th>
                        Fecha
                    </th>
                    
                    <td >
                        {{venta.fecha}}
                    </td>             
                </tr>
                </tr>
            </table>
            <h1>_____________________________________________________________________________________________</h1>
            <h1 class="titulo3">Listado de Productos</h1>

 <table id="invoice">
    <thead>
    <tr>
        <th style="width: 60%;">NOMBRE PRODUCTO</th>
        <th style="width: 60%;">MARCA</th>
        <th style="width: 20%;">CANTIDAD</th>
        <th style="width: 20%;">SUBTOTAL</th>
    </tr>

    </thead>
    <tbody>
        <tr>
    {% for d in venta.detalleventaescuela_set.all %}
            <td>{{ d.producto.nombre }}</td>
            <td>{{ d.producto.marca }}</td>
            <td>{{ d.cantidad}}</td>
            <td>Q.{{ d.sub_total}}</td>
        </tr>


    
    {% endfor %}
</tbody>
    <table>
        <th style="background-color: none; width:80%; font-size: 14px">Total</th>
        <th style="background-color: none; font-size: 14px">Q.{{venta.total}}</th>
    </table>

<br><br><h1 style="text-align: center;">***** Gracias por su compra, es un gusto atenderle *****</h1>

</p><br>




   

    
</body>
</html>

templates/principal/InformeComprasVentas.html
<!DOCTYPE html>
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style type="text/css">
    @page {
            size: landscape;
            margin: 5mm 8mm 5mm 8mm; /* change the margins as you want them to be. */
        }
    .img {
        width: 8cm;
        text-align: center;
        margin: 0;
        }

        #invoice thead tr th {
        
        border: 1px solid black;
        margin: 5px;
        padding-top: 4px;
    }

    #invoice th {
        
        border: 1px solid black;
        margin: 5px;
        text-align: center;
        background-color: #F8C471;
    }

    

    #invoice tbody tr {
        padding: 1;
        text-align: left;
        background-color: #FEF5E7;
        border: 1px solid black;
    }

</style>
</head>

<body>
    <p style="justify-content: center; text-align: center;"><img src="{{ icon }}" class="img">
             <br></p>




{% if rango.tipo_dev == 'General' %}
<p class="head">
    <h1 style="text-align: center;"><l style="font-size: 20px;">Informe de Compras y Ventas del {{rango.fecha_inicio}} al {{rango.fecha_limite}}</h1>

</p><br>
<p class="cuerpo">
<h1 style="text-align: center;"><l style="font-size: 16px;">Compras</h1>
<table id="invoice">
    <thead>
    <tr>
        <th>ID</th>
        <th>PROVEEDOR</th>
        <th>FECHA</th>
        <th>TOTAL</th>

    </thead>
    <tbody>
    {% for d in compras %}
    {% if d.fecha >= rango.fecha_inicio and d.fecha <= rango.fecha_limite  %}
        <tr>
            <td>{{ d.id }}</td>
            <td>{{ d.proveedor }}</td>
            <td>{{ d.fecha }}</td>
            <td>Q.{{ d.total }}</td>
        </tr>
        {% endif %}
        {% endfor %}
   </tbody>
<table id="invoice">
    <thead>
    <tr>
        <th>ID</th>
        <th>ClIENTE</th>
        <th>FECHA</th>
        <th>TOTAL</th>

    </thead>
    <tbody>
    {% for d in ventas %}
    {% if d.fecha >= rango.fecha_inicio and d.fecha <= rango.fecha_limite  %}
        <tr>
            <td>{{ d.id }}</td>
            <td>{{ d.cliente }}</td>
            <td>{{ d.fecha }}</td>
            <td>Q.{{ d.total }}</td>
        </tr>
        {% endif %}
        {% endfor %}
   </tbody>

   <p class="cuerpo">
    
<h1 style="text-align: center;"><l style="font-size: 16px;">Ventas</h1>
<table id="invoice">
    <thead>
    <tr>
        <th>ID</th>
        <th>ESCUELA</th>
        <th>FECHA</th>
        <th>TOTAL</th>

    </thead>
    <tbody>
    {% for d in ventasescuelas %}
    {% if d.fecha >= rango.fecha_inicio and d.fecha <= rango.fecha_limite  %}
        <tr>
            <td>{{ d.id }}</td>
            <td>{{ d.escuela.nombre }}</td>
            <td>{{ d.fecha }}</td>
            <td>Q.{{ d.total }}</td>
        </tr>
        {% endif %}
        {% endfor %}
   </tbody>

<h1 style="text-align: center;"><l style="font-size: 16px;">Ventas a Escuelas</h1>
</p>

<table id="invoice">
    <thead>
    <tr>
        <th style="background-color: none; width:75%; font-size: 14px">Total de Ventas</th>
        <th style="background-color: none; font-size: 14px">Q.{{rango.total_ventas}}</th>
        
        </thead><thead>
        <th style="background-color: none; width:75%; font-size: 14px">Total de Compras</th>
        <th style="background-color: none; font-size: 14px">Q.{{rango.total_compras}}</th>
        
        </thead><thead>
        <th style="background-color: none; width:75%; font-size: 14px">Diferencia</th>
        <th style="background-color: none; font-size: 14px">Q.{{rango.diferencia}}</th>
    <h1 style="text-align: center;"><l style="font-size: 16px;">Resumen</h1>

    </thead>

{% endif %}  



{% if rango.tipo_dev == 'Venta' %}
<p class="head">
    <h1 style="text-align: center;"><l style="font-size: 20px;">Informe de Ventas del {{rango.fecha_inicio}} al {{rango.fecha_limite}}</h1>

</p><br>
<p class="cuerpo">
<table id="invoice">
    <thead>
    <tr>
        <th>ID</th>
        <th>ClIENTE</th>
        <th>FECHA</th>
        <th>TOTAL</th>

    </thead>
    <tbody>
    {% for d in ventas %}
    {% if d.fecha >= rango.fecha_inicio and d.fecha <= rango.fecha_limite  %}
        <tr>
            <td>{{ d.id }}</td>
            <td>{{ d.cliente }}</td>
            <td>{{ d.fecha }}</td>
            <td>Q.{{ d.total }}</td>
        </tr>
        {% endif %}
        {% endfor %}
   </tbody>

   <p class="cuerpo">
    
<h1 style="text-align: center;"><l style="font-size: 16px;">Ventas</h1>
<table id="invoice">
    <thead>
    <tr>
        <th>ID</th>
        <th>ESCUELA</th>
        <th>FECHA</th>
        <th>TOTAL</th>

    </thead>
    <tbody>
    {% for d in ventasescuelas %}
    {% if d.fecha >= rango.fecha_inicio and d.fecha <= rango.fecha_limite  %}
        <tr>
            <td>{{ d.id }}</td>
            <td>{{ d.escuela.nombre }}</td>
            <td>{{ d.fecha }}</td>
            <td>Q.{{ d.total }}</td>
        </tr>
        {% endif %}
        {% endfor %}
   </tbody>
   
<h1 style="text-align: center;"><l style="font-size: 16px;">Ventas a Escuelas</h1>
</p> 
<table id="invoice">
    <thead>
    <tr>
        <th style="background-color: none; width:75%; font-size: 14px">Total de Ventas</th>
        <th style="background-color: none; font-size: 14px">Q.{{rango.total_ventas}}</th>

    </thead>
{% endif %}

{% if rango.tipo_dev == 'Compra' %}
<p class="head">
    <h1 style="text-align: center;"><l style="font-size: 20px;">Informe de Compras del {{rango.fecha_inicio}} al {{rango.fecha_limite}}</h1>

</p><br>
<p class="cuerpo">
<table id="invoice">
    <thead>
    <tr>
        <th>ID</th>
        <th>PROVEEDOR</th>
        <th>FECHA</th>
        <th>TOTAL</th>

    </thead>
    <tbody>
    {% for d in compras %}
    {% if d.fecha >= rango.fecha_inicio and d.fecha <= rango.fecha_limite  %}
        <tr>
            <td>{{ d.id }}</td>
            <td>{{ d.proveedor }}</td>
            <td>{{ d.fecha }}</td>
            <td>Q.{{ d.total }}</td>
        </tr>
        {% endif %}
        {% endfor %}
   </tbody>
   




<table id="invoice">
    <thead>
    <tr>
        <th style="background-color: none; width:75%; font-size: 14px">Total de Compras</th>
        <th style="background-color: none; font-size: 14px">Q.{{rango.total_compras}}</th>

    </thead>
    {% endif %}
</p>




   

    
</body>
</html>

templates/principal/InventarioGeneral.html
<!DOCTYPE html>
<html>
<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style type="text/css">
    @page {
            size: landscape;
            margin: 5mm 8mm 5mm 8mm; /* change the margins as you want them to be. */
        }
    .img {
        width: 8cm;
        text-align: center;
        margin: 0;
        }

        #invoice thead tr th {
        
        border: 1px solid black;
        margin: 5px;
        padding-top: 4px;
    }

    #invoice th {
        
        border: 1px solid black;
        margin: 5px;
        text-align: center;
        background-color: #F8C471;
    }

    

    #invoice tbody tr {
        padding: 1;
        text-align: left;
        background-color: #FEF5E7;
        border: 1px solid black;
    }

</style>
</head>

<body>
    <p style="justify-content: center; text-align: center;"><img src="{{ icon }}" class="img">
             <br></p>


<p class="head">
    <h1 style="text-align: center;"><l style="font-size: 25px;">Informe General de Existencias de Productos</h1>

</p><br>

<p class="cuerpo">

<table id="invoice">
    <thead>
    <tr>
        <th>CÓDIGO MANUAL</th>
        <th>CÓDIGO BARRAS</th>
        <th>NOMBRE</th>
        <th>EXISTENCIA</th>
        <th>MARCA</th>
        <th>PRECIO COSTO</th>
        <th>PRECIO VENTA</th>
        <th>PROVEEDOR</th>

    </thead>
    <tbody>
    {% for d in productos %}
        <tr>
            <td>{{ d.codigo_manual }}</td>
            <td>{{ d.codigo_barra }}</td>
            <td>{{ d.nombre }}</td>
            {% if d.existencia < 6 %}
            <td style="color: red" "width: 20%;" "font-size:bold;"><b>{{ d.existencia }}</b></td>
             {% else%}
            <td style="color: black" "width: 20%;" "font-size:bold;"><b>{{ d.existencia }}</b></td>
            {% endif %}
            <td>{{ d.marca }}</td>
            <td>{{ d.precio_costo}}</td>
            <td>{{ d.precio_venta}}</td>
            <td>{{ d.proveedor.nombre }}</td>


        </tr>
    {% endfor %}
   </tbody>



   

    
</body>
</html>